package com.fleetmanagement.vehicle.grpc

import com.fleetmanagement.proto.vehicle.AssignDriverRequest
import com.fleetmanagement.proto.vehicle.CreateVehicleRequest
import com.fleetmanagement.proto.vehicle.GetVehicleRequest
import com.fleetmanagement.proto.vehicle.ListVehiclesRequest
import com.fleetmanagement.proto.vehicle.ListVehiclesResponse
import com.fleetmanagement.proto.vehicle.LocationUpdate
import com.fleetmanagement.proto.vehicle.StreamLocationRequest
import com.fleetmanagement.proto.vehicle.UpdateLocationRequest
import com.fleetmanagement.proto.vehicle.UpdateVehicleStatusRequest
import com.fleetmanagement.proto.vehicle.Vehicle
import com.fleetmanagement.proto.vehicle.VehicleServiceGrpcKt
import com.fleetmanagement.proto.vehicle.VehicleStatus
import com.fleetmanagement.proto.common.coordinate
import com.fleetmanagement.proto.common.pageInfo
import com.fleetmanagement.proto.vehicle.listVehiclesResponse
import com.fleetmanagement.proto.vehicle.locationUpdate
import com.fleetmanagement.proto.vehicle.vehicle
import com.fleetmanagement.vehicle.interceptor.AUTHENTICATED_USER_KEY
import com.fleetmanagement.vehicle.repository.VehicleRepository
import com.google.protobuf.Empty
import com.google.protobuf.Timestamp
import io.grpc.Status
import io.grpc.StatusException
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.collect
import kotlinx.coroutines.flow.flow
import net.devh.boot.grpc.server.service.GrpcService
import org.slf4j.LoggerFactory
import java.time.Instant
import java.util.UUID
import kotlin.math.sin
import kotlin.math.cos

// =============================================================================
// VEHICLE gRPC SERVICE IMPLEMENTATION
//
// Extends the Kotlin coroutine stub base class generated from vehicle.proto.
// Each RPC pattern has a different method signature:
//
//   Unary:             suspend fun method(request: Req): Resp
//   Server-streaming:  fun method(request: Req): Flow<Resp>
//   Client-streaming:  suspend fun method(requests: Flow<Req>): Resp
//   Bidirectional:     fun method(requests: Flow<Req>): Flow<Resp>
// =============================================================================

@GrpcService
class VehicleGrpcService(
    private val repository: VehicleRepository
) : VehicleServiceGrpcKt.VehicleServiceCoroutineImplBase() {

    private val log = LoggerFactory.getLogger(VehicleGrpcService::class.java)

    // =========================================================================
    // UNARY RPC — CreateVehicle
    // Simple request → response. Most common pattern.
    // =========================================================================
    override suspend fun createVehicle(request: CreateVehicleRequest): Vehicle {
        val caller = AUTHENTICATED_USER_KEY.get()
        log.info("CreateVehicle called by '{}': {} {}", caller?.subject, request.make, request.model)

        val id = UUID.randomUUID().toString()

        // Kotlin DSL builders (generated by protobuf-kotlin plugin)
        // vehicle { } creates a Vehicle.Builder and returns a built Vehicle
        val created = vehicle {
            this.id = id
            make = request.make
            model = request.model
            year = request.year                             // int32
            licensePlate = request.licensePlate            // string
            color = request.color                          // string
            fuelCapacityLiters = request.fuelCapacityLiters // double
            passengerCapacity = request.passengerCapacity  // int32
            status = VehicleStatus.VEHICLE_STATUS_AVAILABLE // enum
            features.addAll(request.featuresList)          // repeated string
            if (request.hasHomeBase()) homeBase = request.homeBase // nested Address
            registeredAt = nowTimestamp()                  // google.protobuf.Timestamp
        }

        repository.save(created)
        return created
    }

    // =========================================================================
    // UNARY RPC — GetVehicle
    // Returns NOT_FOUND status if vehicle doesn't exist.
    // In gRPC, errors are communicated via Status codes (not HTTP codes).
    // =========================================================================
    override suspend fun getVehicle(request: GetVehicleRequest): Vehicle {
        return repository.findById(request.id)
            ?: throw StatusException(
                Status.NOT_FOUND.withDescription("Vehicle '${request.id}' not found")
            )
    }

    // =========================================================================
    // UNARY RPC — ListVehicles
    // Demonstrates: repeated field in response (array of nested objects)
    // =========================================================================
    override suspend fun listVehicles(request: ListVehiclesRequest): ListVehiclesResponse {
        val page = if (request.page < 0) 0 else request.page
        val pageSize = if (request.pageSize <= 0) 20 else request.pageSize

        val result = repository.findAll(request.statusFilter, page, pageSize)

        return listVehiclesResponse {
            vehicles.addAll(result.items)   // repeated Vehicle — array of nested objects
            pageInfo = pageInfo {           // nested PageInfo message
                this.page = page
                this.pageSize = pageSize
                totalCount = result.total
                hasNext = (page + 1) * pageSize < result.total
            }
        }
    }

    // =========================================================================
    // UNARY RPC — AssignDriver
    // Demonstrates: nested object (Driver) passed in request and stored in Vehicle
    // =========================================================================
    override suspend fun assignDriver(request: AssignDriverRequest): Vehicle {
        val existing = repository.findById(request.vehicleId)
            ?: throw StatusException(
                Status.NOT_FOUND.withDescription("Vehicle '${request.vehicleId}' not found")
            )

        val updated = existing.toBuilder()
            .setAssignedDriver(request.driver)  // nested Driver object
            .build()

        repository.save(updated)
        return updated
    }

    // =========================================================================
    // UNARY RPC — UpdateVehicleStatus
    // =========================================================================
    override suspend fun updateVehicleStatus(request: UpdateVehicleStatusRequest): Vehicle {
        val existing = repository.findById(request.vehicleId)
            ?: throw StatusException(
                Status.NOT_FOUND.withDescription("Vehicle '${request.vehicleId}' not found")
            )

        val updated = existing.toBuilder()
            .setStatus(request.status)
            .build()

        repository.save(updated)
        return updated
    }

    // =========================================================================
    // SERVER-STREAMING RPC — StreamLocationUpdates
    //
    // Client sends ONE request; server emits MANY responses via Flow.
    // The client receives location pings as long as the stream stays open.
    //
    // Real use case: mobile app subscribes to a vehicle's live GPS feed.
    // Here we simulate updates every second with slight coordinate drift.
    // =========================================================================
    override fun streamLocationUpdates(request: StreamLocationRequest): Flow<LocationUpdate> = flow {
        log.info("Starting location stream for vehicle: {}", request.vehicleId)

        val vehicle = repository.findById(request.vehicleId)
            ?: throw StatusException(
                Status.NOT_FOUND.withDescription("Vehicle '${request.vehicleId}' not found")
            )

        // Simulate 20 location updates, 500ms apart
        var lat = 52.5200   // Berlin latitude (double)
        var lng = 13.4050   // Berlin longitude (double)
        var fuel = 85

        repeat(20) { i ->
            delay(500L)

            // Simulate circular movement
            lat += sin(i * 0.1) * 0.0005
            lng += cos(i * 0.1) * 0.0005

            val update = locationUpdate {
                vehicleId = request.vehicleId                // string
                coordinates = coordinate {
                    latitude = lat                           // double — WGS84
                    longitude = lng                          // double — WGS84
                    altitudeMeters = 34.0f                   // float
                }
                recordedAt = nowTimestamp()                  // Timestamp (datetime)
                speedKmh = 45.0f + (i % 5) * 3.0f          // float
                headingDegrees = (180f + i * 18f) % 360f    // float
                fuelLevelPercent = fuel - (i / 5)           // int32
            }

            repository.saveLocation(update)
            emit(update)  // Each emit() sends one message to the client
        }

        log.info("Location stream completed for vehicle: {}", request.vehicleId)
    }

    // =========================================================================
    // CLIENT-STREAMING RPC — BatchUpdateLocations
    //
    // Client streams MANY requests; server processes them and replies ONCE.
    // The requests parameter is a Flow — we collect() it to process each item.
    //
    // Real use case: GPS device sends a batch of cached pings when reconnecting.
    // =========================================================================
    override suspend fun batchUpdateLocations(requests: Flow<UpdateLocationRequest>): Empty {
        var count = 0

        requests.collect { req ->   // collect() processes each streamed message
            repository.saveLocation(req.location)
            count++
        }

        log.info("BatchUpdateLocations processed {} location updates", count)
        return Empty.getDefaultInstance()
    }

    // -------------------------------------------------------------------------

    private fun nowTimestamp(): Timestamp {
        val now = Instant.now()
        return Timestamp.newBuilder()
            .setSeconds(now.epochSecond)
            .setNanos(now.nano)
            .build()
    }
}